// 'use client'
// // import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import SideBar from "./components/sidebar"
// import Header from "./components/header";
// import PageWrapper from "./components/pagewrapper";
// // import SearchInput from "./components/SearchInput";


// const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
 
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="flex flex-col" gap-10 items-center p-6>
//           {/* <SearchInput /> */}
//           <div className="flex flex-col items-center w-full">

//           </div>


//         <div className="flex min-h-screen">
//           <SideBar />
//           <Header />
//           <PageWrapper children= {children}>
           
//           </PageWrapper>
//         </div>
//         </div>
//       </body>
//     </html>
//   );
// }
'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sidebar";
import Header from "./components/header";
import PageWrapper from "./components/pagewrapper";
// import SearchInput from "./components/SearchInput";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const hasGap = true;
  const gapClassName = hasGap ? "gap-10" : "";

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`flex ${gapClassName} min-h-screen`}>
          <SideBar />
          <div className="flex flex-col w-full">
            <Header />
            <PageWrapper>{children}</PageWrapper>
          </div>
        </div>
      </body>
    </html>
  );
}
