'use client'
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sidebar"
import Header from "./components/header";
import PageWrapper from "./components/pagewrapper";
import { useState } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [toggleCollapse, setToggleCollapse] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <SideBar toggleCollapse={toggleCollapse} />
          <Header toggleCollapse={toggleCollapse} setToggleCollapse={setToggleCollapse}/>
          <PageWrapper toggleCollapse={toggleCollapse}>
            {children}
          </PageWrapper>
        </div>
      </body>
    </html>
  );
}
